# Configuration Schema for RemNote Flashcard Generator Settings
type: object
required: [llm, remnote, generation, output]
properties:
  llm:
    type: object
    required: [provider, temperature, max_tokens]
    properties:
      provider:
        type: string
        enum: [anthropic, openai]
        default: "anthropic"
        description: "LLM provider to use"
      model:
        type: string
        enum: ["claude-3-5-sonnet-20241022", "claude-3-sonnet-20240229", "claude-3-haiku-20240307", "gpt-4", "gpt-3.5-turbo"]
        default: "claude-3-5-sonnet-20241022"
        description: "Specific model to use"
      temperature:
        type: number
        minimum: 0.0
        maximum: 2.0
        default: 0.3
        description: "Temperature for generation randomness"
      max_tokens:
        type: integer
        minimum: 100
        maximum: 8000
        default: 2000
        description: "Maximum tokens per request"
      retry_attempts:
        type: integer
        minimum: 1
        maximum: 10
        default: 3
        description: "Number of retry attempts for failed requests"
      retry_delay:
        type: number
        minimum: 1
        maximum: 60
        default: 2
        description: "Delay between retries in seconds"
  
  remnote:
    type: object
    properties:
      default_folder:
        type: string
        default: "ML System Design"
        description: "Default folder name for RemNote import"
      include_hierarchy:
        type: boolean
        default: true
        description: "Whether to preserve hierarchical structure"
  
  generation:
    type: object
    properties:
      cards_per_concept:
        type: object
        properties:
          min:
            type: integer
            minimum: 1
            maximum: 10
            default: 3
          max:
            type: integer
            minimum: 1
            maximum: 15
            default: 5
      card_types:
        type: object
        properties:
          concept:
            type: boolean
            default: true
          basic:
            type: boolean
            default: true
          cloze:
            type: boolean
            default: true
          descriptor:
            type: boolean
            default: true
      include_examples:
        type: boolean
        default: true
        description: "Whether to include examples in card generation"
      difficulty_distribution:
        type: object
        properties:
          beginner:
            type: number
            minimum: 0.0
            maximum: 1.0
            default: 0.3
          intermediate:
            type: number
            minimum: 0.0
            maximum: 1.0
            default: 0.5
          advanced:
            type: number
            minimum: 0.0
            maximum: 1.0
            default: 0.2
  
  output:
    type: object
    properties:
      format:
        type: string
        enum: [remnote_text, remnote_api]
        default: "remnote_text"
        description: "Output format type"
      include_stats:
        type: boolean
        default: true
        description: "Include generation statistics in output"
      include_metadata:
        type: boolean
        default: false
        description: "Include metadata in the output"
  
  prompts:
    type: object
    properties:
      system_prompt:
        type: string
        description: "System prompt for LLM generation"
        default: |
          You are an expert in creating spaced repetition flashcards.
          Generate cards that are atomic, clear, and testable.
          Focus on understanding over memorization.
